[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --prefix frontend"]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "npx serve -s frontend/dist -l ${PORT:-3000} --no-clipboard"
