[phases.setup]
nixPkgs = ["python311", "gcc", "nodejs-18_x"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements/api.txt",
  "if [ \"$SERVICE_TYPE\" = 'landing-page' ]; then cd landing-page && npm ci && npm run build; fi"
]

[start]
cmd = "python3 railway_start.py"
